# Generated by Django 5.1.4 on 2024-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(choices=[('basic', 'Basic Fun ($199)'), ('premium', 'Premium Magic ($299)'), ('deluxe', 'Deluxe Party ($399)')], max_length=50),
        ),
    ]
