# Generated by Django 5.1.4 on 2025-01-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_datarequest_package_booking_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
